import { useEffect, useState, type ChangeEvent } from "react";
import { withBase } from "../lib/links";
import { excerptParts } from "../lib/search";

interface Props {
  base: string;
}

// the part of Pagefind's browser API used here; the module is generated by the build, so it has no types to import
interface PagefindResultData {
  url: string;
  meta: { title: string };
  excerpt: string;
}

interface Pagefind {
  options: (options: { baseUrl: string }) => Promise<void>;
  init: () => Promise<void>;
  // resolves to null when a newer search superseded this one
  debouncedSearch: (term: string) => Promise<{
    results: { data: () => Promise<PagefindResultData> }[];
  } | null>;
}

interface Found {
  term: string;
  results: PagefindResultData[];
}

export default function Search({ base }: Props) {
  const [query, setQuery] = useState("");
  const [pagefind, setPagefind] = useState<Pagefind | null>(null);
  const [unavailable, setUnavailable] = useState(false);
  const [found, setFound] = useState<Found | null>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    setQuery(new URLSearchParams(location.search).get("q") ?? "");
    // Pagefind derives its bundle directory from this module URL;
    // options() and init() don't reject when index files fail to load (searches do, handled below), so the import is the only failure to catch here, and it fails when there is no index because `npm run build` was not run
    import(/* @vite-ignore */ withBase(base, "/pagefind/pagefind.js")).then(
      async (module: Pagefind) => {
        // result URLs are indexed from the site root, so prefix them with the base path
        await module.options({ baseUrl: base });
        await module.init();
        setPagefind(module);
      },
      () => setUnavailable(true),
    );
  }, [base]);

  useEffect(() => {
    const term = query.trim();
    if (!pagefind || term === "") {
      setFound(null);
      return;
    }
    // loading each result's data is async too, so a newer query can still overtake a search Pagefind already returned
    let current = true;
    pagefind
      .debouncedSearch(term)
      .then(async (search) => {
        if (search === null) {
          return;
        }
        const results = await Promise.all(
          search.results.map((result) => result.data()),
        );
        if (current) {
          setFound({ term, results });
          setFailed(false);
        }
      })
      .catch((error: unknown) => {
        console.error(error);
        if (current) {
          setFailed(true);
        }
      });
    return () => {
      current = false;
    };
  }, [pagefind, query]);

  const onChange = (event: ChangeEvent<HTMLInputElement>) => {
    const next = event.target.value;
    setQuery(next);
    const url = new URL(location.href);
    if (next === "") {
      url.searchParams.delete("q");
    } else {
      url.searchParams.set("q", next);
    }
    history.replaceState(history.state, "", url);
  };

  return (
    <div>
      <label htmlFor="search-query" className="sr-only">
        Search posts
      </label>
      <input
        id="search-query"
        type="search"
        value={query}
        onChange={onChange}
        placeholder="Search posts"
        className="w-full rounded-md border border-transparent bg-surface px-3 py-2 placeholder:text-muted focus:border-fg focus:outline-none"
      />
      {unavailable ? (
        <p className="mt-6 text-muted">
          The search index is generated by <code>npm run build</code>, so search
          only works on a built site.
        </p>
      ) : (
        <>
          <p role="status" className="mt-6 text-sm text-muted">
            {failed
              ? "Search failed. Reload the page to try again."
              : found &&
                `${found.results.length} ${found.results.length === 1 ? "result" : "results"} for "${found.term}"`}
          </p>
          {!failed && found && found.results.length > 0 && (
            <ul className="mt-4 border-t border-rule">
              {found.results.map((result) => (
                <li
                  key={result.url}
                  className="border-b border-rule py-4 break-keep break-words"
                >
                  <a
                    href={result.url}
                    className="marker-draw text-[1.0625rem] font-semibold hover:stroke-drawn"
                  >
                    {result.meta.title}
                  </a>
                  <p className="mt-1 text-sm text-muted">
                    {excerptParts(result.excerpt).map((part, index) =>
                      part.marked ? (
                        <mark key={index}>{part.text}</mark>
                      ) : (
                        part.text
                      ),
                    )}
                  </p>
                </li>
              ))}
            </ul>
          )}
        </>
      )}
    </div>
  );
}
